### ISSUE TITLE
Assignment 2 - Git Cheat Sheet!

### ISSUE THREAD

**Issue by lizthrilla** [justindowney/suncoast#2]
Hello, World.
In your first assignment you will end up with a git cheat sheet published on the web.

You will create a simple website that will provide git commands and prompts that you will be using during this course.  

Objectives
Get to know your text editor
Introduce yourself to working on the command line
Get comfortable with Git!
Write some HTML
Publish a web page
Requirements
Have git, hub, node, app-app installed. We should have done this together in class. Reminder: you only have to install these tools once.

All of your HTML (and CSS if you do epic mode) should be formatted cleanly and consistently (use your editor to your advantage).

If you have experience with existing HTML/CSS frameworks (bootstrap, bulma, etc) you may not use them for these assignments.

Explorer Mode
  Follow all of the setup instructions.
  Provide 5 git commands in a list format of your choice.
  Deploy your site.

Adventure Mode
Provide 5 git commands and 5 command line commands.  
Use at least one image (a screenshot of your terminal with the commands) somewhere on the page.
  Learn about and investigate the a to add (at least 2) more pages to your site.
  Re-deploy your site.
  Read more about CSS.

Epic Mode
 Provide 10 commands for each.
  Research the id and class HTML attributes.
  Use valid CSS to style the page (in the neighborhood of a couple dozen CSS declarations).
  Create a full layout for your page (heading, navigation, sidebar, footer, etc.).
  Use more complex CSS selectors than we covered in class, e.g. attribute selectors or sibling selectors.

**Comment by justindowney** [comment]
https://thimbleprojects.org/justindowney/666722/

**Comment by justindowney** [comment]
https://github.com/justindowney/git-cheat-sheet

Gavin helped me! thank you

**Comment by lizthrilla** [comment]
Your homework was marked: **Exceeds Expectations**

![Woah](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5d5eae07a7d338c96b9a2cc704bc5ec7f53d072c/woah.gif)
> &ldquo;Woah&rdquo;
__&mdash; via **[Jason L Perry](https://gifs.suncoast.io/venerations/2)**__
